# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json tsconfig.json ./
RUN npm ci --ignore-scripts --silent

# Copy source and build
COPY src ./src
RUN npm run build

# Remove dev dependencies
RUN npm prune --production

ENV NODE_ENV=production

# Start the MCP server over stdio
ENTRYPOINT ["node", "dist/index.js"]
